services:

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    # https://docs.docker.com/reference/compose-file/services/#network_mode
    network_mode: "host"
    # networks:
    #   - host
    # "Published ports are discarded when using host network mode"
    # ports:
    #   - "8080:8080"
    #   - "443:443"

  nginx-prometheus-exporter:
    container_name: nginx-prometheus-exporter
    image: nginx/nginx-prometheus-exporter:latest
    restart: always
    environment:
      - NGINX_SERVER=nginx:8080
      - '--nginx.scrape-uri=http://localhost/stub_status'
    network_mode: "host"
    # networks:
    #   - host
    # ports:
    #   - "9113:9113"

  # source https://prometheus.io/docs/prometheus/latest/installation/
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    # TODO find a way to use the correct user "nobody"
    # https://github.com/prometheus/prometheus/blob/main/Dockerfile#L17
    # user: "nobody"
    user: root
    restart: always
    volumes:
      # https://prometheus.io/docs/prometheus/latest/installation/#volumes-bind-mount
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      # https://prometheus.io/docs/prometheus/latest/installation/#save-your-prometheus-data
      # TODO commented because it's an empty directory for artifact
      # - ./prometheus/data:/prometheus
    network_mode: "host"
    # networks:
    #   - host
    # ports:
    #   - 9090:9090
